apiVersion: 1
 
contactPoints:
  - orgId: 1
    name: ntfy-heimnetz
    receivers:
      - uid: ntfy-heimnetz-webhook
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://ntfy:80/Heimnetz
          httpMethod: POST
          message: '{{ template "ntfy.message" . }}'