apiVersion: 1
contactPoints:
    - orgId: 1
      name: ntfy
      receivers:
        - uid: cfhqngj75zq4ge
          type: webhook
          settings:
            httpMethod: POST
            url: http://ntfy:80/Heimnetz
          disableResolveMessage: false