apiVersion: 1

templates:
  - orgId: 1
    name: ntfy
    template: |
      {{ define "ntfy.message" -}}
      {{ if eq .Status "firing" -}}
      🔴 ALARM aktiv
      {{ else -}}
      ✅ Wieder normal
      {{ end -}}
      {{ (index .Alerts 0).Annotations.summary }}
      Seit: {{ (index .Alerts 0).StartsAt.Format "02.01.2006 15:04" }} Uhr
      {{- end }}
