global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # --- home-pi ---
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'home-pi'

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'home-pi'

  # --- backup-pi ---
  - job_name: 'cadvisor-rpi2'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.20:8080']   # ← RPi 2 IP eintragen
        labels:
          instance: 'backup-pi'

  - job_name: 'node-exporter-rpi2'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.20:9100']   # ← RPi 2 IP eintragen
        labels:
          instance: 'backup-pi'